steps:
  # Build API image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'infra/docker/Dockerfile.api'
      - '-t'
      - 'us-central1-docker.pkg.dev/simplebuildpro/simplebuildpro/api:latest'
      - '.'
    id: 'build-api'

  # Build Web image  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'infra/docker/Dockerfile.web'
      - '-t'
      - 'us-central1-docker.pkg.dev/simplebuildpro/simplebuildpro/web:latest'
      - '.'
    id: 'build-web'

images:
  - 'us-central1-docker.pkg.dev/simplebuildpro/simplebuildpro/api:latest'
  - 'us-central1-docker.pkg.dev/simplebuildpro/simplebuildpro/web:latest'

logsBucket: 'gs://simplebuildpro_cloudbuild'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: GCS_ONLY

timeout: '1800s'
